### ISSUE TITLE
Sponsorship To Dos

### ISSUE THREAD

**Issue by govvin** [pistangmapa/pnm20-coord#1]
- [x] publish final sponsorship tiers
- [x] update names, contact info of 2020 prospective sponsors
- [x] draft letter for prospective sponsors
- [x] send out letters by end of W9

**Comment by maning** [comment]
Status as of Feb 27.

* formal letters sent -13, 
* confirmed sponsors - 2
* balance to hit -  5100 usd

<img width="508" alt="Screenshot 2020-02-27 11 39 38" src="https://user-images.githubusercontent.com/353700/75411168-469ee000-5959-11ea-85e1-4d551e463fd0.png">

**Comment by maning** [comment]
**Week 10 update**

<img width="303" alt="Screenshot 2020-03-06 12 26 23" src="https://user-images.githubusercontent.com/353700/76051443-c6eec200-5fa5-11ea-86ff-9eff8ef2ef11.png">

- Assuming all committed amount will be received, we are in a good position to run the conference.
- We are still open for sponsorship which we can use to expand the scholarship support.  But we won't be actively cold calling new/potential sponsors.  
- If there are orgs who will express support, please send us contact details.

**Next actions**
- Followup all those that were sent formal letters without a reply by week 12.
